# ==============================================
# Configuration Starship [https://starship.rs/]
#
# Par: PatBoud
# ==============================================

# Paramètres globaux
scan_timeout = 10
add_newline = true

# ???????????????????????????
# NE FONCTIONNE PAS
#
# Palette de couleurs
palette = "pat"

[palettes.pat]
# Définition des couleurs de la palette
orange = "179"
bleu = "32"
# ???????????????????????????

[hostname]
format = "@(bold white)[$hostname](bold 179) "

[username]
style_user = "green bold"
style_root = "black bold"
format = "[$user]($style)"
show_always = true

[directory]
style = "32"
truncation_length = 10
truncation_symbol = "…/"
